# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('topic', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature')], max_length=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('upvotes', models.IntegerField(default=1)),
                ('is_feature', models.BooleanField(default=False)),
            ],
        ),
    ]
