# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('topic', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature')], max_length=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('upvotes', models.IntegerField(default=1)),
                ('is_feature', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('1', 'To Do'), ('2', 'Doing'), ('3', 'Done')], default='To Do', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket'),
        ),
    ]
